spring:
  application:
    name: spring-cloud-zuul
server:
  port: 8073
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
zuul:
  routes:
   user:
      path:  /user/**
      service-id: userservice
      #url: "http://localhost:8071/"
   notes: 
      path: /notes/**
      service-id: noteservice
      #url: "http://localhost:8072/"
   labels: 
      path: /labels/**
      service-id: noteservice
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000000 

ribbon:  
  ReadTimeout: 600000000  
  ConnectTimeout: 600000000  

  host: 
    connect-timeout-millis: 100000000
    socket-timeout-millis: 600000000